### ISSUE TITLE
新版本sdk问题

### ISSUE THREAD

**Issue by Licarey** [onlyloveyd/AndroidDeviceMonitorPlugin#1]
新版本sdk /tools下没有monitor 怎么解决

**Comment by onlyloveyd** [comment]
具体是哪个版本 我看看去

**Comment by Licarey** [comment]
@onlyloveyd 没事 就是sdk高的版本，/tools下没有monitor，低版本的sdk是有的

**Comment by onlyloveyd** [comment]
@Licarey 是的，从AS菜单上移除以后，慢慢地就是被抛弃并替代
